version: "3.8"

services:
  backend:
    container_name: conferencer-backend
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
    volumes:
      - ./backend:/app
    restart: always
