spring.datasource.url=jdbc:postgresql://localhost:5432/conferencer_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
spring.security.oauth2.client.registration.google.client-id=957813325622-dvrciioe73t4dorpokic7evbfihh6kim.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
#security.basic.enabled=false
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect