name: Build Frontend

on:
  push:
    branches:
      - main
    paths:
      - "frontend/**"

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies & Build
        working-directory: ./frontend
        run: |
          npm install
          npm run build

    outputs:
      build_status: success
