name: Deploy Backend

on:
  workflow_run:
    workflows: ["Build Backend"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy Flask Backend
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Set Up SSH Agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Backend
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} "
            cd ${{ secrets.DOCKER_COMPOSE_PATH }} &&
            git pull origin main &&
            docker-compose down &&
            docker-compose build &&
            docker-compose up -d
          "
        

          