name: Do Nothing CI/CD

on:
  push:
    branches:
      - main

jobs:
  do-nothing:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Do Nothing
        run: echo "This workflow does nothing!"
